<?php

return [
    'product_fallback' => 'Produkt',
    'condition' => [
        'new' => 'neu',
        'like_new' => 'wie neu',
        'used_good' => 'gebraucht, guter Zustand',
        'used_fair' => 'gebraucht, ordentlicher Zustand',
        'used_poor' => 'gebraucht, schlechter Zustand',
        'broken' => 'defekt / zur Reparatur',
        'unknown' => 'Zustand nicht bestätigt',
    ],
    'strategy' => [
        'quick_sale' => 'Schnellverkaufs-',
        'recommended' => 'empfohlenen',
        'ambitious' => 'ambitionierten',
    ],
    'title' => '{identity} — {condition}',
    'intro' => 'Zum Verkauf: {identity}.',
    'condition_heading' => 'Zustand',
    'condition_disclosure' => 'Zustand: {condition}.',
    'age' => 'Alter: {age_months} Monate.',
    'age_unknown' => 'Das Alter wurde nicht angegeben.',
    'accessories_heading' => 'Zubehör',
    'included' => 'Enthaltenes Zubehör: {values}.',
    'included_none' => 'Es ist kein enthaltenes Zubehör bestätigt.',
    'included_unknown' => 'Enthaltenes Zubehör wurde nicht bestätigt.',
    'missing' => 'Bekanntes fehlendes Zubehör: {values}.',
    'missing_none' => 'Es wurde kein fehlendes Zubehör gemeldet.',
    'missing_unknown' => 'Fehlendes Zubehör wurde nicht bestätigt.',
    'defects_heading' => 'Mängel',
    'defects' => 'Angegebene Mängel: {values}.',
    'defects_none' => 'Es wurden keine Mängel gemeldet.',
    'defects_unknown' => 'Mängel wurden nicht bestätigt.',
    'price_heading' => 'Preis',
    'asking_price' => 'Ziel-Angebotspreis: {price}.',
    'guidance_note' => 'Der Verkäufer hat diesen Angebotspreis anhand der {strategy} Preisspanne gewählt. Er ist kein garantierter Transaktionspreis.',
];
