<?php

return [
    'product_fallback' => 'Product',
    'condition' => [
        'new' => 'new',
        'like_new' => 'like new',
        'used_good' => 'used, good condition',
        'used_fair' => 'used, fair condition',
        'used_poor' => 'used, poor condition',
        'broken' => 'broken / for repair',
        'unknown' => 'condition not confirmed',
    ],
    'strategy' => [
        'quick_sale' => 'quick-sale',
        'recommended' => 'recommended',
        'ambitious' => 'ambitious',
    ],
    'title' => '{identity} — {condition}',
    'intro' => 'For sale: {identity}.',
    'condition_heading' => 'Condition',
    'condition_disclosure' => 'Condition: {condition}.',
    'age' => 'Age: {age_months} months.',
    'age_unknown' => 'Age was not provided.',
    'accessories_heading' => 'Accessories',
    'included' => 'Included accessories: {values}.',
    'included_none' => 'No accessories are confirmed as included.',
    'included_unknown' => 'Included accessories were not confirmed.',
    'missing' => 'Known missing accessories: {values}.',
    'missing_none' => 'No missing accessories were reported.',
    'missing_unknown' => 'Missing accessories were not confirmed.',
    'defects_heading' => 'Defects',
    'defects' => 'Disclosed defects: {values}.',
    'defects_none' => 'No defects were reported.',
    'defects_unknown' => 'Defects were not confirmed.',
    'price_heading' => 'Price',
    'asking_price' => 'Target asking price: {price}.',
    'guidance_note' => 'The seller chose this asking price using the {strategy} guidance range. It is not a guaranteed transaction price.',
];
