<?php

return [
    'product_fallback' => 'Producto',
    'condition' => [
        'new' => 'nuevo',
        'like_new' => 'como nuevo',
        'used_good' => 'usado, en buen estado',
        'used_fair' => 'usado, en estado aceptable',
        'used_poor' => 'usado, en mal estado',
        'broken' => 'averiado / para reparar',
        'unknown' => 'estado sin confirmar',
    ],
    'strategy' => [
        'quick_sale' => 'de venta rápida',
        'recommended' => 'recomendado',
        'ambitious' => 'ambicioso',
    ],
    'title' => '{identity} — {condition}',
    'intro' => 'En venta: {identity}.',
    'condition_heading' => 'Estado',
    'condition_disclosure' => 'Estado: {condition}.',
    'age' => 'Antigüedad: {age_months} meses.',
    'age_unknown' => 'No se indicó la antigüedad.',
    'accessories_heading' => 'Accesorios',
    'included' => 'Accesorios incluidos: {values}.',
    'included_none' => 'No hay accesorios confirmados como incluidos.',
    'included_unknown' => 'No se confirmaron los accesorios incluidos.',
    'missing' => 'Accesorios que se sabe que faltan: {values}.',
    'missing_none' => 'No se informó de accesorios faltantes.',
    'missing_unknown' => 'No se confirmaron los accesorios faltantes.',
    'defects_heading' => 'Defectos',
    'defects' => 'Defectos declarados: {values}.',
    'defects_none' => 'No se informó de defectos.',
    'defects_unknown' => 'No se confirmaron los defectos.',
    'price_heading' => 'Precio',
    'asking_price' => 'Precio de venta objetivo: {price}.',
    'guidance_note' => 'El vendedor eligió este precio de venta usando el rango {strategy}. No es un precio de transacción garantizado.',
];
