<?php

return [
    'product_fallback' => 'Produit',
    'condition' => [
        'new' => 'neuf',
        'like_new' => 'comme neuf',
        'used_good' => 'd’occasion, bon état',
        'used_fair' => 'd’occasion, état correct',
        'used_poor' => 'd’occasion, mauvais état',
        'broken' => 'en panne / à réparer',
        'unknown' => 'état non confirmé',
    ],
    'strategy' => [
        'quick_sale' => 'de vente rapide',
        'recommended' => 'recommandée',
        'ambitious' => 'ambitieuse',
    ],
    'title' => '{identity} — {condition}',
    'intro' => 'À vendre : {identity}.',
    'condition_heading' => 'État',
    'condition_disclosure' => 'État : {condition}.',
    'age' => 'Âge : {age_months} mois.',
    'age_unknown' => 'L’âge n’a pas été indiqué.',
    'accessories_heading' => 'Accessoires',
    'included' => 'Accessoires inclus : {values}.',
    'included_none' => 'Aucun accessoire inclus n’est confirmé.',
    'included_unknown' => 'Les accessoires inclus n’ont pas été confirmés.',
    'missing' => 'Accessoires manquants connus : {values}.',
    'missing_none' => 'Aucun accessoire manquant n’a été signalé.',
    'missing_unknown' => 'Les accessoires manquants n’ont pas été confirmés.',
    'defects_heading' => 'Défauts',
    'defects' => 'Défauts déclarés : {values}.',
    'defects_none' => 'Aucun défaut n’a été signalé.',
    'defects_unknown' => 'Les défauts n’ont pas été confirmés.',
    'price_heading' => 'Prix',
    'asking_price' => 'Prix de vente cible : {price}.',
    'guidance_note' => 'Le vendeur a choisi ce prix à partir de la fourchette {strategy}. Il ne s’agit pas d’un prix de transaction garanti.',
];
