<?php

return [
    'product_fallback' => 'Proizvod',
    'condition' => [
        'new' => 'novo',
        'like_new' => 'kao novo',
        'used_good' => 'polovno, dobro stanje',
        'used_fair' => 'polovno, zadovoljavajuće stanje',
        'used_poor' => 'polovno, loše stanje',
        'broken' => 'neispravno / za popravku',
        'unknown' => 'stanje nije potvrđeno',
    ],
    'strategy' => [
        'quick_sale' => 'brze prodaje',
        'recommended' => 'preporučenog',
        'ambitious' => 'ambicioznog',
    ],
    'title' => '{identity} — {condition}',
    'intro' => 'Na prodaju: {identity}.',
    'condition_heading' => 'Stanje',
    'condition_disclosure' => 'Stanje: {condition}.',
    'age' => 'Starost: {age_months} meseci.',
    'age_unknown' => 'Starost nije navedena.',
    'accessories_heading' => 'Dodatna oprema',
    'included' => 'Uključena dodatna oprema: {values}.',
    'included_none' => 'Nije potvrđena uključena dodatna oprema.',
    'included_unknown' => 'Uključena dodatna oprema nije potvrđena.',
    'missing' => 'Poznata oprema koja nedostaje: {values}.',
    'missing_none' => 'Nije prijavljena oprema koja nedostaje.',
    'missing_unknown' => 'Oprema koja nedostaje nije potvrđena.',
    'defects_heading' => 'Nedostaci',
    'defects' => 'Prijavljeni nedostaci: {values}.',
    'defects_none' => 'Nisu prijavljeni nedostaci.',
    'defects_unknown' => 'Nedostaci nisu potvrđeni.',
    'price_heading' => 'Cena',
    'asking_price' => 'Ciljana oglašena cena: {price}.',
    'guidance_note' => 'Prodavac je ovu oglašenu cenu izabrao na osnovu raspona {strategy}. To nije garantovana prodajna cena.',
];
