<?php

return [
    'capacity_baseline' => [
        'tenant_page_size' => 50,
        'probes' => [
            'platform_dashboard_cold' => [
                'maximum_queries' => 12,
                'maximum_database_milliseconds' => 1000,
                'maximum_wall_milliseconds' => 1500,
            ],
            'analysis_operations_count' => [
                'maximum_queries' => 1,
                'maximum_database_milliseconds' => 500,
                'maximum_wall_milliseconds' => 750,
            ],
            'tenant_analysis_index' => [
                'maximum_queries' => 2,
                'maximum_database_milliseconds' => 500,
                'maximum_wall_milliseconds' => 750,
            ],
        ],
    ],
    'queue_throughput' => [
        'default_jobs' => 100,
        'maximum_jobs' => 5000,
        'default_timeout_seconds' => 60,
        'maximum_timeout_seconds' => 300,
        'receipt_ttl_seconds' => 900,
        'poll_interval_milliseconds' => 100,
        'cache_key_prefix' => 'performance:queue-throughput:v1',
        'budgets' => [
            'minimum_throughput_per_second' => 5.0,
            'maximum_p95_latency_milliseconds' => 15000,
            'maximum_p99_latency_milliseconds' => 30000,
        ],
    ],
    'analysis_pipeline_workload' => [
        'enabled' => (bool) env(
            'PERFORMANCE_ANALYSIS_WORKLOAD_ENABLED',
            false,
        ),
        'cache_store' => env(
            'PERFORMANCE_ANALYSIS_WORKLOAD_CACHE_STORE',
        ),
        'default_scenarios' => 20,
        'maximum_scenarios' => 250,
        'default_permit_ttl_seconds' => 900,
        'maximum_permit_ttl_seconds' => 3600,
        'lock_seconds' => 10,
        'lock_wait_seconds' => 3,
        'cache_key_prefix' => 'performance:analysis-pipeline-workload:v1',
        'header' => 'X-Procura-Analysis-Workload-Permit',
        'budgets' => [
            'version' => 'analysis-pipeline-workload-budget:v1',
            'minimum_throughput_per_second' => 0.25,
            'maximum_draft_p95_milliseconds' => 2000,
            'maximum_submit_p95_milliseconds' => 2000,
            'maximum_pipeline_p95_milliseconds' => 60000,
            'maximum_failure_rate_basis_points' => 0,
        ],
    ],
    'analysis_pipeline_metrics' => [
        'enabled' => (bool) env('PERFORMANCE_ANALYSIS_METRICS_ENABLED', true),
        'retention_days' => (int) env(
            'PERFORMANCE_ANALYSIS_METRICS_RETENTION_DAYS',
            30,
        ),
        'default_purge_batch_size' => 1000,
        'maximum_purge_batch_size' => 5000,
        'default_report_window_minutes' => 60,
        'maximum_report_window_minutes' => 43_200,
        'default_report_samples' => 1000,
        'maximum_report_samples' => 10_000,
        'default_minimum_samples' => 20,
        'maximum_minimum_samples' => 1000,
        'budgets' => [
            'version' => 'analysis-pipeline-stage-budget:v1',
            'maximum_failure_rate_basis_points' => 0,
            'maximum_provider_analysis_p95_milliseconds' => 30_000,
            'maximum_product_matching_p95_milliseconds' => 5000,
            'maximum_comparable_selection_p95_milliseconds' => 10_000,
            'maximum_price_estimation_p95_milliseconds' => 10_000,
            'maximum_risk_assessment_p95_milliseconds' => 5000,
            'maximum_finalization_p95_milliseconds' => 10_000,
            'maximum_total_p95_milliseconds' => 60_000,
        ],
    ],
    'sell_price_intelligence_metrics' => [
        'enabled' => (bool) env('PERFORMANCE_SELL_METRICS_ENABLED', true),
        'metrics_version' => 'sell-price-intelligence-metrics:v1',
        'retention_days' => (int) env(
            'PERFORMANCE_SELL_METRICS_RETENTION_DAYS',
            30,
        ),
        'default_purge_batch_size' => 1000,
        'maximum_purge_batch_size' => 5000,
        'default_report_window_minutes' => 60,
        'maximum_report_window_minutes' => 43_200,
        'default_report_samples' => 1000,
        'maximum_report_samples' => 10_000,
        'default_minimum_samples' => 20,
        'maximum_minimum_samples' => 1000,
        'minimum_scopes_per_operation' => 2,
        'budgets' => [
            'version' => 'sell-price-intelligence-stage-budget:v1',
            'maximum_scope_discovery_p95_milliseconds' => 1000,
            'maximum_comparable_selection_p95_milliseconds' => 10_000,
            'maximum_selection_persistence_p95_milliseconds' => 5000,
            'maximum_price_band_estimation_p95_milliseconds' => 5000,
            'maximum_price_band_persistence_p95_milliseconds' => 5000,
            'maximum_total_p95_milliseconds' => 30_000,
        ],
    ],
];
